### ISSUE TITLE
CSS of the card template interfering with progress bar

### ISSUE THREAD

**Issue by andrearicci** [trgkanki/remaining_time#12]
# remaining time is not showing in some indented decks

## I have a "current" deck wich is composed of 4 indented decks. Remianing time 2.1 shows the remaiming time only for the first one, when a card from other decks is shown I only see a white bar (dark mode). When a card from the first deck is shown, the bar comes back.

> A clear and concise description of what the bug is.

## I just "automatically" updated to 2.1, This didn't happen before.

> Steps to reproduce the behavior:

1. create a deck with sub-decks
2. study now
3. the bar correctly appears whenever a card from the firs deck shows up
4. the bar is empty when a card from the other decks is shown

## Expected behavior
the bar shoud always work.

## Actual behavior

> the bar works only with the first deck

## Anki/OS versions

- OS: * win 10-1904*
- Anki version *2.1.28 (7d8818f8)*

## Additional context

Here are 3 screenshots, the current deck is shown at the bottom. Only the first is working.

![Annotazione 2020-08-27 203605](https://user-images.githubusercontent.com/1193266/91742521-adc27900-ebb6-11ea-96a8-c7c47fd51552.png)
![Annotazione 2020-08-27 204715](https://user-images.githubusercontent.com/1193266/91742533-b1ee9680-ebb6-11ea-8a39-708a995d7543.png)
![Annotazione 2020-08-27 203514](https://user-images.githubusercontent.com/1193266/91742538-b3b85a00-ebb6-11ea-8272-1c8119350df2.png)

and this is the deck's hierarchy:
![immagine](https://user-images.githubusercontent.com/1193266/91742915-4658f900-ebb7-11ea-89d4-f3f67806f49b.png)

**Comment by phu54321** [comment]
Sorry for late reply :( I was having quite a chaotic days recently...

------

This is weird. I also am using the addon with multiple subdecks and I don't see a problem here.

![image](https://user-images.githubusercontent.com/775265/93005017-e33c6e80-f587-11ea-9854-5b0483770a22.png)

This issue is due to review tracker classifying your reviews as 'unknown'. ([code](https://github.com/trgkanki/remaining_time/blob/4d41b2cff2adcfd459efa6660ae276aa5a15cb51/jssrc/updater.ts#L108)) To track down the problem I have to know how your remaining card count changes (three blue/red/green number at the bottom) and how the progress bar reacts accordingly.

Could you upload a video of your studying?

**Comment by andrearicci** [comment]
Here you are.
[2020-09-13 12-57-32.zip](https://github.com/trgkanki/remaining_time/files/5213955/2020-09-13.12-57-32.zip)
Thank you

**Comment by phu54321** [comment]
This is weird. I guess error occurs whenever you're reviewing new cards, but that's just a guess.

1) Would you try using this build?
[build.zip](https://github.com/trgkanki/remaining_time/files/5228870/build.zip)

2) If that doesn't work, then could you send me

- a list of installed addons
- export of that problematic deck (send via phu54321@naver.com). export with scheduling data.

**Comment by andrearicci** [comment]
this are the plugs:
![immagine](https://user-images.githubusercontent.com/1193266/93304825-ee003900-f7fd-11ea-847d-6eba6f614879.png)
to install your build I deleted first the installed one, I went to "install from file" an I get 
![immagine](https://user-images.githubusercontent.com/1193266/93304943-18ea8d00-f7fe-11ea-81bf-7cdcb3365710.png)
so I reinstalled it with the magic number (and the error is still there).
I'm sending you my decks, but I don't know if it includes scheduling data (I exported them without media)

[collection-2020-09-16@09-28-53-nomedia.zip](https://github.com/trgkanki/remaining_time/files/5230539/collection-2020-09-16%4009-28-53-nomedia.zip)

**Comment by phu54321** [comment]
Your card template has this CSS

```
svg > text { fill: #fff !important; }
svg > path { stroke: #fff !important; }
svg > circle[r="5"] { fill: #fff !important; }
svg > circle[r="3.25"] { fill: #2d2d2d !important; }
```

Removing `svg > path { stroke: #fff !important; }` fixes the issue. This issue is caused by external CSS interfering with progress bar styling. For a complete fix we need to employ [shadow DOM](https://developer.mozilla.org/ko/docs/Web/Web_Components/Using_shadow_DOM) to isolate styling between components.

Changing the isue title accordingly
