### ISSUE TITLE
Colors are all the same shade of green

### ISSUE THREAD

**Issue by hkhiem** [trgkanki/remaining_time#13]
# Bug report

## Describe the bug

> While rating cards, the progress bar shows only shades of green. I have no idea how to change the colors anymore since the new update.

## Reproduction step

> Steps to reproduce the behavior:

1. Go to deck e.g. AnKing
2. Click on study now
3. Start rating cards Good and Again

## Expected behavior

> Blue for Good and Red for Again as it did before. 

## Actual behavior

>
![image](https://user-images.githubusercontent.com/71027270/92998635-80dc6300-f4e0-11ea-9f13-5c4fa4f63f5b.png)

## Anki/OS versions

- OS: Windows 10
- Anki version 2.1.26 (also occurred on 2.1.33)

## Additional context

Additionally, where is the file where you can modify the colors for the progress bar?

**Comment by phu54321** [comment]
This is intentional. Learning new cards are now shown as green. Sadly this is not really fixable due to changes in implementation defail.

If you want the older behavior you should use the old version. I've uploaded the old version [here](https://github.com/trgkanki/remaining_time/raw/cd611d23b3350d7caace2ce0e51bda536386f160/rt_legacy_purepy.zip). Sorry for the answer :(

**Comment by hkhiem** [comment]
Oh! I see. Thank you for the reply @phu54321
