### ISSUE TITLE
error when starting ANKI

### ISSUE THREAD

**Issue by brunogomes81** [trgkanki/remaining_time#18]
error loading

First congratulations on the extension, I liked it a lot.
I use the extension on another computer with the same version of ANKI, but in this case here the following message appears:
I am a novice user at ANKI, is this an error that can be corrected?
Thank you very much in advance.

![image](https://user-images.githubusercontent.com/72533369/95405202-8bc2c180-08ed-11eb-89db-63a45ab6cab2.png)

Ao carregar 'Remaining time for Anki 21 ':
Traceback (most recent call last):
File "aqt\addons.py", line 60, in loadAddons
File "C:\Users\\Mndows 10\AppData\Roaming
\Anki2\addon521\1508357010\_init_.py", line 24, in <module>
from .utils import openChangelog
File "C:\Users\Windows 10\AppData\Roaming
\Anki2\addon521\1508357010\utils\openChangelog.py", line 27, in <module>
from anki.utils import noBundledLibs
ImportError: cannot import name 'noBundIedLibs'

**Comment by phu54321** [comment]
Please follow the template

# Bug report

## Describe the bug

> A clear and concise description of what the bug is.

## Reproduction step

> Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior

> A clear and concise description of what you expected to happen.

## Actual behavior

> If applicable, add screenshots to help explain your problem.

## Anki/OS versions

- OS: *[ex: macOS Catalina, Windows 10, Ubuntu 18.04]*
- Anki version *[ex: 2.1.23]*

## Additional context

Add any other context about the problem here.
