### ISSUE TITLE
Gap in the timeline!

### ISSUE THREAD

**Issue by TheDemystifier** [trgkanki/remaining_time#20]
# Bug report

## Describe the bug

> If I press the edit button while reviewing, this shows up as a huge red bar on the timeline/bar. Even if the editing only took seconds. Somehow, the addon registers it as a lapsed card that took a lot of time.

![](https://i.imgur.com/rHDz6SU.png)

## Reproduction step

> Steps to reproduce the behavior:

1. Go to 'Reviews'
2. Click on 'edit while you're reviewing'
3. Scroll down to 'the bar after you close the edit panel'
4. See the red bar on the bar

## Expected behavior

> Editing a card shouldn't affect the bar's progress behavior!

## Actual behavior

> Editing a card messes up the timeline.

## Anki/OS versions

- OS: Windows 10 64bits
- Anki Version 2.1.24 (359b9f5c)
- Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

**Comment by TheDemystifier** [comment]
On a second thought, I think that's because the addon also counts the time not-reviewing, right? If you leave the deck and come back 30 minutes later, that 30 minute gap will show up like that, correct?

Is this a bug or a feature?

**Comment by phu54321** [comment]
```
I think that's actually because the addon also counts the time spent not-reviewing, right?
```

Correct. This is a feature.

```
Is it possible to only count time when you're reviewing.
```
May I ask you why? I think addon should visualize the time you've left. While I agree that filling up the entire progress bar space with pale giant block of 4hr segment, addon should say that you've left the review for a considerable amount of time.

This is some alternative visualization I'm thinking of

- Instead of showing long pause as-is, clamp them to 30minute max (Note: remaining time calculation already clamps long pauses to 5 minutes. This 30min clamp is for visualization only). 30minute is arbitary, but this seems long enough to show how much you've left the reviews, but short enough to not disturb entire progress bar visualization.

**Comment by TheDemystifier** [comment]
Ah, Ok! I was under the impression that every deck would have its own progress bar, in which case, each deck should only count the time spent reviewing the particular deck, not elsewhere.

**Comment by phu54321** [comment]
Oh okay I havent thought of multi deck reviewing scenario. That would be a use case that could be considered.

**Comment by phu54321** [comment]
Implementing multi-deck scenario requires a considerable amount of works. Meanwhile, an indicator for super-long suspended time has been added, like this

![image](https://user-images.githubusercontent.com/775265/96706206-3d272400-13d1-11eb-99b0-40d2337eb1e7.png)

**Comment by phu54321** [comment]
> Implementing multi-deck scenario requires a considerable amount of works.

This would require a different meta-isssue. Closing this issue with https://github.com/trgkanki/remaining_time/commit/b52fa4ac2a6130f644271c62c1c2fb8e473b782a.
