### ISSUE TITLE
Program will not show

### ISSUE THREAD

**Issue by Sue9112** [trgkanki/remaining_time#35]
# Bug report I made sure to have the version for Anki 2.1 but the program bar does not show when I am doing my decks. 

## Describe the bug Version 2.1.22 (131d37dc) is the Anki version I have, and I use a MacOS Catalina

> A clear and concise description of what the bug is.

## Reproduction step

> Steps to reproduce the behavior:

## Expected behavior

> A clear and concise description of what you expected to happen.

## Actual behavior

> If applicable, add screenshots to help explain your problem.

## Anki/OS versions

- OS: *[ex: macOS Catalina, Windows 10, Ubuntu 18.04]*
- Anki version *[ex: 2.1.23]*

## Additional context

> Add any other context about the problem here.

**Comment by thiswillbeyourgithub** [comment]
@Sue9112  You did not fill any of the information required. The developper (aka not me) will obviously have to ask you to give way more information otherwise you're wasting his time. 

@phu54321 Just chiming in to say that for whatever reason your addon works on my desktop (2.1.35) AND my ankidroid phone but does not appear on my ankidroid tablet. They have both 1.14.2 ankidroid. It's been a while so I don't know what started this. Any idea how I could fix this? I tried toggling a bunch of things in the advanced ankidroid section to no effect. Should I try reinstalling or something? Any idea of a way to reset this?

**Comment by phu54321** [comment]
Postponing till exam (2021.01.08 KST)
