### ISSUE TITLE
Latest Update Causing Desktop to Crash 

### ISSUE THREAD

**Issue by Stu6** [trgkanki/remaining_time#9]
# Bug report

## Describe the bug

> After installing latest remaining_time update, anki does not load with it enabled

## Reproduction step

> Steps to reproduce the behavior:

1. Enable the add-on
2. Close Anki
3. Try to load anki 2.1.31
4. Error pops up when anki attempts to load

## Expected behavior

> I expected anki to load normally as in the past

## Actual behavior

> Anki never loads; I disabled all other add-on's and still get this error. Anki loads normally while holding shift to bypass loading add-ons.

![Anki Error Message](https://user-images.githubusercontent.com/70181214/91110313-0cca4000-e643-11ea-9515-8d122022ebd0.PNG)

## Anki/OS versions

- OS: Windows 10 Version 1909
- Anki version 2.1.31

**Comment by phu54321** [comment]
Thanks for the report.

- You can update the addon to fix the issue. Hotfix now online.
- This error is due to Anki's code change on 2.1.30. (https://github.com/ankitects/anki/commit/06a0b1ee73c22c35777309155e7035c25e750490)
- This issue has been resolved on https://github.com/trgkanki/remaining_time/commit/3046e3c91b6e4a53279ba34f2c4a97c4a7258c43

I'll leave this issue open for a while, as I think many people would experience the same problem.
